title_primary: "鱼类观测研究所" # the bigger text
title_secondary: "lz233's blog" # the smaller text
keywords:

twitter: lz__233
rss: atom.xml
weibo: #username/id
instagram: #username
github: lz233
telegram: https://forms.gle/WGYKB8ij61aEH8BWA
coolapk:
cloudmusic: 299866209
acfun: 13046631
zhihu: lz233.sakura
email: ohayou@lz233.ac.cn

about: /about
# Choose the comment service according to your need.
# Please do not use the two services at the same time.
livere: # [data-uid] on livere.com
disqus: # [short_name] on disqus.com
dove: # For fun ONLY. Set to true to 'disable' comments on your site.
utterances: true

# Set true to show the page indicator.
showPageCount: true

# Set true to show category or tags behind post titles
showCategories: true
showTags: true

# Color scheme
themeStyle: light # light/dark
